// Generated from packages/mathjax-core/src/latex-to-svg-core.ts and packages/mathjax-core/src/native-latex-to-svg.ts by scripts/build-latex-to-svg.mjs.
// Do not edit this file by hand.
(function (global) {
  var coreExports = {};
  var coreModule = { exports: coreExports };
  var exports = coreExports;
  var module = coreModule;
  "use strict";
  Object.defineProperty(exports, "__esModule", { value: true });
  exports.zeroViewBox = exports.svgOutputOptions = exports.defaultTexPackages = void 0;
  exports.fallbackText = fallbackText;
  exports.renderLatexToSvgJson = renderLatexToSvgJson;
  exports.renderLatexToSvgPayload = renderLatexToSvgPayload;
  exports.parseLatexToSvgJson = parseLatexToSvgJson;
  exports.sanitizeMarkup = sanitizeMarkup;
  exports.parseViewBox = parseViewBox;
  exports.hasMathErrorMarkup = hasMathErrorMarkup;
  exports.hasMathErrorNode = hasMathErrorNode;
  exports.defaultTexPackages = [
      "base",
      "ams",
      "newcommand",
      "noundefined",
      "require",
      "autoload",
      "configmacros",
      "mhchem"
  ];
  exports.svgOutputOptions = {
      fontCache: "none"
  };
  exports.zeroViewBox = {
      minX: 0,
      minY: 0,
      width: 0,
      height: 0
  };
  function fallbackText(tex, standalone) {
      return standalone ? String.raw `\[${tex}\]` : String.raw `\(${tex}\)`;
  }
  function renderLatexToSvgJson(runtime, tex, options = {}) {
      return JSON.stringify(renderLatexToSvgPayload(runtime, tex, options));
  }
  function renderLatexToSvgPayload(runtime, tex, options = {}) {
      var _a;
      const source = safeText(tex);
      const standalone = Boolean(options.standalone);
      const fallback = fallbackText(source, standalone);
      try {
          const fontSize = positiveNumber(options.fontSize, 16);
          const root = runtime.convert(source, {
              display: standalone,
              em: fontSize,
              ex: fontSize / 2,
              scale: positiveNumber(options.scale, 1)
          });
          const svg = runtime.findAll(root, "svg")[0];
          if (!svg) {
              throw new Error("MathJax did not return an SVG node.");
          }
          const group = runtime.findAll(svg, "g")[0];
          if (group) {
              runtime.setAttribute(group, "fill", "currentColor");
              runtime.setAttribute(group, "stroke", "currentColor");
          }
          const markup = sanitizeMarkup(runtime.outerHTML(svg));
          const mathError = runtime.hasMathError(root) || hasMathErrorMarkup(markup);
          return {
              ok: !mathError,
              svg: markup,
              markup,
              viewBox: (_a = parseViewBox(markup)) !== null && _a !== void 0 ? _a : exports.zeroViewBox,
              fallbackText: mathError ? fallback : null,
              error: mathError ? "MathJax reported a TeX parse error." : null
          };
      }
      catch (error) {
          return {
              ok: false,
              svg: "",
              markup: "",
              viewBox: exports.zeroViewBox,
              fallbackText: fallback,
              error: error instanceof Error ? error.message : String(error)
          };
      }
  }
  function parseLatexToSvgJson(json) {
      var _a, _b, _c, _d;
      const payload = JSON.parse(json);
      const markup = sanitizeMarkup(String((_b = (_a = payload.markup) !== null && _a !== void 0 ? _a : payload.svg) !== null && _b !== void 0 ? _b : ""));
      const viewBox = (_d = (_c = parsePayloadViewBox(payload.viewBox)) !== null && _c !== void 0 ? _c : parseViewBox(markup)) !== null && _d !== void 0 ? _d : exports.zeroViewBox;
      const ok = Boolean(payload.ok) && !hasMathErrorMarkup(markup);
      return {
          ok,
          svg: markup,
          markup,
          viewBox,
          fallbackText: nullableString(payload.fallbackText),
          error: nullableString(payload.error)
      };
  }
  function sanitizeMarkup(markup) {
      return String(markup || "")
          .replace(/<script[\s\S]*?<\/script>/gi, "")
          .replace(/\son[a-z]+\s*=\s*"[^"]*"/gi, "")
          .replace(/\son[a-z]+\s*=\s*'[^']*'/gi, "")
          .replace(/\son[a-z]+\s*=\s*[^>\s]+/gi, "")
          .replace(/javascript:/gi, "");
  }
  function parseViewBox(markup) {
      const match = markup.match(/viewBox\s*=\s*["']([^"']+)["']/i);
      if (!match) {
          return undefined;
      }
      const values = match[1]
          .split(/[\s,]+/)
          .filter(Boolean)
          .map((value) => Number(value));
      if (values.length !== 4 || values.some((value) => !Number.isFinite(value))) {
          return undefined;
      }
      return {
          minX: values[0],
          minY: values[1],
          width: values[2],
          height: values[3]
      };
  }
  function hasMathErrorMarkup(markup) {
      return /data-mml-node=["']merror["']/i.test(markup) || /<mjx-merror\b/i.test(markup);
  }
  function hasMathErrorNode(node) {
      var _a, _b, _c;
      if (!node || typeof node !== "object") {
          return false;
      }
      const candidate = node;
      if (((_a = candidate.attributes) === null || _a === void 0 ? void 0 : _a["data-mml-node"]) === "merror") {
          return true;
      }
      const children = (_c = (_b = candidate.children) !== null && _b !== void 0 ? _b : candidate.childNodes) !== null && _c !== void 0 ? _c : [];
      return children.some(hasMathErrorNode);
  }
  function positiveNumber(value, fallback) {
      const parsed = Number(value);
      return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
  }
  function safeText(value) {
      return String(value == null ? "" : value);
  }
  function nullableString(value) {
      return typeof value === "string" && value.length > 0 ? value : null;
  }
  function parsePayloadViewBox(value) {
      if (typeof value === "string") {
          return parseViewBox(`viewBox="${value}"`);
      }
      if (typeof value !== "object" || value === null) {
          return undefined;
      }
      const raw = value;
      const minX = Number(raw.minX);
      const minY = Number(raw.minY);
      const width = Number(raw.width);
      const height = Number(raw.height);
      if (![minX, minY, width, height].every(Number.isFinite)) {
          return undefined;
      }
      return {
          minX,
          minY,
          width,
          height
      };
  }
  coreExports = coreModule.exports;
  var LatexToSvgCore = coreExports;
  var hostExports = {};
  var hostModule = { exports: hostExports };
  exports = hostExports;
  module = hostModule;
  "use strict";
  Object.defineProperty(exports, "__esModule", { value: true });
  exports.installLatexToSvgBridge = installLatexToSvgBridge;
  exports.createGlobalRuntime = createGlobalRuntime;
  function installLatexToSvgBridge(globalObject) {
      const runtime = createGlobalRuntime(globalObject);
      globalObject.MathRenderLatexToSvg = {
          renderJSON(tex, options) {
              return LatexToSvgCore.renderLatexToSvgJson(runtime, tex, options);
          }
      };
  }
  function createGlobalRuntime(globalObject) {
      return {
          convert(tex, options) {
              ensureReady(globalObject);
              return globalObject.MathJax.startup.document.convert(tex, options);
          },
          findAll(node, name) {
              ensureReady(globalObject);
              return globalObject.MathJax.startup.adaptor.tags(node, name);
          },
          setAttribute(node, name, value) {
              ensureReady(globalObject);
              globalObject.MathJax.startup.adaptor.setAttribute(node, name, value);
          },
          outerHTML(node) {
              ensureReady(globalObject);
              return globalObject.MathJax.startup.adaptor.outerHTML(node);
          },
          hasMathError(node) {
              return LatexToSvgCore.hasMathErrorNode(node);
          }
      };
  }
  function ensureReady(globalObject) {
      var _a, _b;
      if (globalObject.__MathRenderLatexToSvgReady) {
          return;
      }
      const mathJax = globalObject.MathJax;
      if (!mathJax) {
          throw new Error("MathJax is not loaded.");
      }
      mathJax.config.startup.input = ["tex"];
      mathJax.config.startup.output = "svg";
      mathJax.config.startup.adaptor = "liteAdaptor";
      mathJax.config.startup.handler = "HTMLHandler";
      mathJax.config.startup.document = "";
      mathJax.config.startup.typeset = false;
      mathJax.config.tex = (_a = mathJax.config.tex) !== null && _a !== void 0 ? _a : {};
      mathJax.config.svg = (_b = mathJax.config.svg) !== null && _b !== void 0 ? _b : {};
      mathJax.config.tex.packages = [...LatexToSvgCore.defaultTexPackages];
      mathJax.config.svg.fontCache = LatexToSvgCore.svgOutputOptions.fontCache;
      mathJax.startup.defaultReady();
      globalObject.__MathRenderLatexToSvgReady = true;
  }
  hostExports = hostModule.exports;
  if (typeof hostExports.installLatexToSvgBridge !== "function") {
    throw new Error("Generated LaTeX-to-SVG bridge is missing installLatexToSvgBridge().");
  }
  hostExports.installLatexToSvgBridge(global);
}(this));
