/**
 * Node.js API for @dongyuzhao/math-renderer.
 *
 * For JSC usage the pre-built IIFE bundle is located at
 * swift/Sources/MathRenderer/Resources/MathJax/mathjax-renderer.js
 * (generated by `npm run build`).
 */

'use strict';

const { liteAdaptor } = require('mathjax-full/js/adaptors/liteAdaptor.js');
const { RegisterHTMLHandler } = require('mathjax-full/js/handlers/html.js');
const { TeX } = require('mathjax-full/js/input/tex.js');
const { SVG } = require('mathjax-full/js/output/svg.js');
const { mathjax } = require('mathjax-full/js/mathjax.js');
const { AllPackages } = require('mathjax-full/js/input/tex/AllPackages.js');

const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);

const tex = new TeX({ packages: AllPackages });
const svgOutput = new SVG({ fontCache: 'local' });
const doc = mathjax.document('', { InputJax: tex, OutputJax: svgOutput });

function extractViewBox(markup) {
  const m = markup.match(/viewBox\s*=\s*["']([^"']+)["']/i);
  return m ? m[1] : null;
}

function sanitize(markup) {
  return markup
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/\son[a-zA-Z]+\s*=\s*"[^"]*"/g, '')
    .replace(/\son[a-zA-Z]+\s*=\s*'[^']*'/g, '')
    .replace(/\son[a-zA-Z]+\s*=\s*[^>\s]+/g, '')
    .replace(/javascript:/gi, '');
}

/**
 * Render a LaTeX formula to an SVG string.
 *
 * @param {string} latex  - LaTeX source (without surrounding $ delimiters)
 * @param {object} [options]
 * @param {boolean} [options.standalone=false] - display (block) mode when true
 * @param {number}  [options.fontSize=16]      - font size in px (affects em size)
 * @returns {{ markup: string, viewBox: string|null, ok: boolean, error: string|null }}
 */
function renderToSVG(latex, options = {}) {
  const em = typeof options.fontSize === 'number' && options.fontSize > 0
    ? options.fontSize : 16;
  const ex = em / 2;
  const display = options.standalone === true;

  try {
    const node = doc.convert(latex, { display, em, ex, containerWidth: 1200 });
    const markup = sanitize(adaptor.outerHTML(node));
    return { markup, viewBox: extractViewBox(markup), ok: true, error: null };
  } catch (err) {
    return {
      markup: '',
      viewBox: null,
      ok: false,
      error: String(err && err.message ? err.message : err),
      fallbackText: display ? `$$${latex}$$` : `$${latex}$`,
    };
  }
}

module.exports = { renderToSVG };

