#!/usr/bin/env node
/**
 * Bundles src/mathjax-jsc.js into a single IIFE that can be evaluated inside
 * JavaScriptCore (no require, no Node built-ins).
 *
 * Output: swift/Sources/MathRenderer/Resources/MathJax/mathjax-renderer.js
 *         android/mathrenderer/src/main/assets/MathJax/mathjax-renderer.js
 */

import { build } from 'esbuild';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { mkdirSync, copyFileSync } from 'fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const swiftOut = join(root, 'swift', 'Sources', 'MathRenderer', 'Resources', 'MathJax');
const androidOut = join(root, 'android', 'mathrenderer', 'src', 'main', 'assets', 'MathJax');

mkdirSync(swiftOut, { recursive: true });
mkdirSync(androidOut, { recursive: true });

await build({
  entryPoints: [join(root, 'src', 'mathjax-jsc.js')],
  bundle: true,
  format: 'iife',
  platform: 'neutral',
  target: ['es2017'],
  outfile: join(swiftOut, 'mathjax-renderer.js'),
  minify: false,
  define: {
    'process.env.NODE_ENV': '"production"',
  },
  banner: {
    js: '/* Auto-generated by npm run build — do not edit manually */',
  },
});

// Mirror the bundle into the Android assets folder
copyFileSync(
  join(swiftOut, 'mathjax-renderer.js'),
  join(androidOut, 'mathjax-renderer.js')
);

console.log('✅  mathjax-renderer.js written to:');
console.log('   ', swiftOut);
console.log('   ', androidOut);
