#!/usr/bin/env node
/**
 * Build script for JSC/Android assets.
 *
 * 1. esbuild bundles src/mathjax-jsc.js → mathjax-renderer.js
 *    (pure MathJax engine IIFE; exposes globalThis.MathJax)
 * 2. src/mathjax-bridge.js is copied as-is to both output dirs
 *    (no bundling needed — it has no imports)
 *
 * Output dirs:
 *   swift/Sources/MathRenderer/Resources/MathJax/
 *   android/mathrenderer/src/main/assets/MathJax/
 */

import { build } from 'esbuild';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { mkdirSync, copyFileSync } from 'fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const swiftOut = join(root, 'swift', 'Sources', 'MathRenderer', 'Resources', 'MathJax');
const androidOut = join(root, 'android', 'mathrenderer', 'src', 'main', 'assets', 'MathJax');

mkdirSync(swiftOut, { recursive: true });
mkdirSync(androidOut, { recursive: true });

// ── 1. Bundle the MathJax engine ─────────────────────────────────────────────

await build({
  entryPoints: [join(root, 'src', 'mathjax-jsc.js')],
  bundle: true,
  format: 'iife',
  platform: 'neutral',
  target: ['es2017'],
  outfile: join(swiftOut, 'mathjax-renderer.js'),
  minify: false,
  define: {
    'process.env.NODE_ENV': '"production"',
  },
  banner: {
    js: '/* Auto-generated by npm run build — do not edit manually */',
  },
});

copyFileSync(
  join(swiftOut, 'mathjax-renderer.js'),
  join(androidOut, 'mathjax-renderer.js')
);

// ── 2. Copy the bridge (no bundling — zero imports) ───────────────────────────

copyFileSync(join(root, 'src', 'mathjax-bridge.js'), join(swiftOut, 'mathjax-bridge.js'));
copyFileSync(join(root, 'src', 'mathjax-bridge.js'), join(androidOut, 'mathjax-bridge.js'));

console.log('✅  mathjax-renderer.js + mathjax-bridge.js written to:');
console.log('   ', swiftOut);
console.log('   ', androidOut);
